Alterado regra no step Validate tag belongs to develop branch.

diff --git a/.github/workflows/03-cd-release.yml b/.github/workflows/03-cd-release.yml
--- a/.github/workflows/03-cd-release.yml
+++ b/.github/workflows/03-cd-release.yml
@@ -37,12 +37,12 @@ jobs:
       - name: 01 - Checkout application
         uses: actions/checkout@v4
 
-      - name: 02 - Validate tag belongs to main
+      - name: 02 - Validate tag belongs to develop branch
         run: |
-          git fetch origin main
+          git fetch origin develop
 
-          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
-            echo "::error::The tag '$GITHUB_REF_NAME' is not on the main branch."
+          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/develop; then
+            echo "::error::The tag '$GITHUB_REF_NAME' is not on the develop branch."
             exit 1
           fi
 
